//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address_New
    {
        public int add_new_id { get; set; }
        public string billing_address1 { get; set; }
        public string billing_address2 { get; set; }
        public string billing_state { get; set; }
        public string billing_city { get; set; }
        public string billing_zipcode { get; set; }
        public string shipping_address1 { get; set; }
        public string shipping_address2 { get; set; }
        public string shipping_state { get; set; }
        public string shipping_city { get; set; }
        public string shipping_zipcode { get; set; }
    }
}
