//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSWeb
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class posEntities : DbContext
    {
        public posEntities()
            : base("name=posEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<FacebookUser> FacebookUsers { get; set; }
        public virtual DbSet<Revision> Revisions { get; set; }
        public virtual DbSet<OrderDetail> OrderDetails { get; set; }
        public virtual DbSet<KoronaStore> KoronaStores { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<StoreProduct> StoreProducts { get; set; }
        public virtual DbSet<LiveTracking> LiveTrackings { get; set; }
        public virtual DbSet<Rider> Riders { get; set; }
        public virtual DbSet<RiderOrder> RiderOrders { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<Store> Stores { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Log> Logs { get; set; }
        public virtual DbSet<Store_Product> Store_Product { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    
        public virtual ObjectResult<get_OrderDetailsForEmail_Result> get_OrderDetailsForEmail(string orderid)
        {
            var orderidParameter = orderid != null ?
                new ObjectParameter("orderid", orderid) :
                new ObjectParameter("orderid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_OrderDetailsForEmail_Result>("get_OrderDetailsForEmail", orderidParameter);
        }
    
        public virtual ObjectResult<get_OrdersListForIndex_Result> get_OrdersListForIndex()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_OrdersListForIndex_Result>("get_OrdersListForIndex");
        }
    
        public virtual ObjectResult<report_sales_simple_Result> report_sales_simple(Nullable<int> days)
        {
            var daysParameter = days.HasValue ?
                new ObjectParameter("days", days) :
                new ObjectParameter("days", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<report_sales_simple_Result>("report_sales_simple", daysParameter);
        }
    
        public virtual ObjectResult<report_customer_basic_Result> report_customer_basic()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<report_customer_basic_Result>("report_customer_basic");
        }
    
        public virtual ObjectResult<dbo_get_ProductsListForIndex_Result> dbo_get_ProductsListForIndex()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<dbo_get_ProductsListForIndex_Result>("dbo_get_ProductsListForIndex");
        }
    }
}
