//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public int notificationId { get; set; }
        public Nullable<int> riderId { get; set; }
        public string body { get; set; }
        public string title { get; set; }
    
        public virtual RiderUser RiderUser { get; set; }
    }
}
