//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public int orderDetailsId { get; set; }
        public Nullable<int> quantity { get; set; }
        public string title { get; set; }
        public string productId { get; set; }
        public string price { get; set; }
        public Nullable<int> orderId { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
