//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public string OrderId { get; set; }
        public string UserId { get; set; }
        public string StoreId { get; set; }
        public Nullable<double> Total { get; set; }
        public string ShippingAddress { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public string Zipcode { get; set; }
        public string Phone { get; set; }
        public string OrderType { get; set; }
        public Nullable<System.DateTime> deliveryDate { get; set; }
        public string OrderLocation { get; set; }
        public Nullable<System.DateTime> CreatedDatetime { get; set; }
        public Nullable<bool> AcceptedByRider { get; set; }
        public Nullable<bool> Shipped { get; set; }
        public string trackingNo { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<bool> Cancelled { get; set; }
        public Nullable<System.DateTime> CancelledDateTime { get; set; }
        public Nullable<bool> Completed { get; set; }
        public Nullable<System.DateTime> CompletedDateTime { get; set; }
    }
}
