//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class RiderUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RiderUser()
        {
            this.Notifications = new HashSet<Notification>();
        }
    
        public int riderId { get; set; }
        public string riderUsername { get; set; }
        public string riderPassword { get; set; }
        public string registration { get; set; }
        public string model { get; set; }
        public string color { get; set; }
        public string phone { get; set; }
        public Nullable<bool> IsAvailable { get; set; }
        public string DeviceId { get; set; }
        public string email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Notification> Notifications { get; set; }
    }
}
