//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class RiderOrder
    {
        public int Id { get; set; }
        public string RiderId { get; set; }
        public string CustomerId { get; set; }
        public string OrderId { get; set; }
        public Nullable<System.DateTime> AcceptedDateTime { get; set; }
        public Nullable<bool> PickedByRider { get; set; }
        public Nullable<System.DateTime> PickedByRiderDateTime { get; set; }
    }
}
