//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoreProduct
    {
        public int Id { get; set; }
        public string StoreId { get; set; }
        public string Korona_ProductId { get; set; }
        public string Korona_ProductNumber { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Category { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<int> Stock { get; set; }
        public string ImageUrl { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public Nullable<System.DateTime> UpdatedDateTime { get; set; }
    }
}
